### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by SylarRuby** [kubrickology/mailchimp-v3-api#10]
Hi. Nice plugin and thanks for sharing it. Can you update the documentation with the params to pass to the constructor, as seen here https://github.com/bobvanluijt/mailchimp-v3-api/blob/c2e246b7fa9452de36f792e63bcdc9ac03d96f6c/mailchimp-v3-api.js#L36

Other users maybe using `us16` instead of `us12`. Just saying. Thanks

**Comment by bobvanluijt** [comment]
Thanks, not sure I follow. This is already in the docs ;-)

https://github.com/bobvanluijt/mailchimp-v3-api/tree/c2e246b7fa9452de36f792e63bcdc9ac03d96f6c#usage
