### ISSUE TITLE
Develop `PATCH`, `PUT`, `DELETE`?

### ISSUE THREAD

**Issue by viki53** [kubrickology/mailchimp-v3-api#2]
Hi,

I just began using your module, but I got stuck when trying to use the `put` method.

Then I looked at your code and saw that the `put`, `patch` and `delete` methods are empty.

Is there any way you could copy and paste what's in the `post` method (and adapt the HTTP method) to make those work?

Thanks!

P.S.: If you need me to do a PR for that, please let me know

**Comment by bobvanluijt** [comment]
Yeah, sorry about that. Let me fix that for you. I'll do it asap

**Comment by bobvanluijt** [comment]
This is fixed: https://github.com/kubrickology/mailchimp-v3-api/commit/3ec2af0cd8f80904ea4c27b8ce81742b8a776725
