### ISSUE TITLE
it's set "debug" to true even if i set { debug: false }

### ISSUE THREAD

**Issue by motizharfati** [kubrickology/mailchimp-v3-api#4]
OLD Code: 
if (typeof i.debug === 'undefined') {
   this.debug = false;
} else {
   this.debug = true;
}

Should be changed to:
if (typeof i.debug === 'boolean') {
   this.debug =  i.debug;
} else {
   this.debug = false;
}

**Comment by bobvanluijt** [comment]
Fixed https://github.com/kubrickology/mailchimp-v3-api/commit/59d38d7b5b27848f0b84201f96e840a61fc8e5d9
