### ISSUE TITLE
Capitalize the method in batch requests!

### ISSUE THREAD

**Issue by tony-gutierrez** [kubrickology/mailchimp-v3-api#6]
FYI: https://github.com/thorning/node-mailchimp/issues/10

**Comment by bobvanluijt** [comment]
Hi @tony-gutierrez, sorry for being late here. Any update on this? Is this still a bug or should it be resolved?

**Comment by tony-gutierrez** [comment]
As far as I can tell, the best path forward is to make sure that the method names are always capitalized. Even though they are just string parameters of the batch api call, Mailchimp is pretending like they are being used as **actual request methods**, and need to conform to the spec for http requests (capitalized).

**Comment by tony-gutierrez** [comment]
I haven't confirmed this is a bug in your current implementation, I just wasted a ton of time on discovering it, and tried to spread the word.

**Comment by bobvanluijt** [comment]
Thanks, all is in caps
