### ISSUE TITLE
Error with api v3

### ISSUE THREAD

**Issue by iLeonelPerea** [kubrickology/mailchimp-v3-api#8]
Hi everyone.

I am doing a POST, trying to add a member to a List but shows the following error:

{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"API Key Missing","status":401,"detail":"Your request did not include an API key.","instance":""}

do you know what happend?

Tnks

**Comment by bobvanluijt** [comment]
Did you forget to add a key? See the example in the readme file

**Comment by iLeonelPerea** [comment]
I am running your module in my own react code. 

I am running the script from the terminal and it works.
But when I run from the browser it doesn't work.

Here is my code:

```
import MAILCHIMP_V3 from "mailchimp-v3-api";

let mailchimpAPI = new MAILCHIMP_V3({
  key: "xxxxxxxxxxxxxxx-xxxx",
  debug: true,
  location: "us14"
});

mailchimpAPI
	.get("/lists")
	.then(function(response){
		console.log(response);
	});
```

Any idea?

that is the implementation that I have

https://github.com/Tinker-Ware/homepage/blob/feature/add-easy-forms/src/containers/HomePage.js

**Comment by bobvanluijt** [comment]
Hmm, this seems to be all good. Can you do a manual request with that key?

**Comment by iLeonelPerea** [comment]
Hi...

I tried different modules, but it works only from the terminal. but if I
run from the web browser it doesnt work :(

**Comment by M1chaelTran** [comment]
hey @iLeonelPerea 
check your path is correct.
I too thought there is something wrong with the library.. but it turns out that I had /list instead of `/lists`
Also, make sure that the location matches up with the key. (the location is shown at the end of the key).

It is working perfectly for me.

**Comment by bobvanluijt** [comment]
is this resolved @iLeonelPerea ?
